version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  frontend:
    image: adamconder/adamconder-frontend
    container_name: frontend
    environment:
      VIRTUAL_HOST: frontend.service
